package indexathor;
// Generated 5 feb. 2021 17:32:04 by Hibernate Tools 4.3.1



/**
 * Songs generated by hbm2java
 */
public class Songs  implements java.io.Serializable {


     private SongsId id;
     private String album;
     private Integer duracion;
     private String ano;
     private String ruta;

    public Songs() {
    }

	
    public Songs(SongsId id, String ruta) {
        this.id = id;
        this.ruta = ruta;
    }
    public Songs(SongsId id, String album, Integer duracion, String ano, String ruta) {
       this.id = id;
       this.album = album;
       this.duracion = duracion;
       this.ano = ano;
       this.ruta = ruta;
    }
   
    public SongsId getId() {
        return this.id;
    }
    
    public void setId(SongsId id) {
        this.id = id;
    }
    public String getAlbum() {
        return this.album;
    }
    
    public void setAlbum(String album) {
        this.album = album;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }
    public String getAno() {
        return this.ano;
    }
    
    public void setAno(String ano) {
        this.ano = ano;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }




}


