package indexathor;
// Generated 2 feb. 2021 19:41:54 by Hibernate Tools 4.3.1



/**
 * Songs generated by hbm2java
 */
public class Songs  implements java.io.Serializable {


     private SongsId id;
     private String album;
     private Double duracion;
     private String ano;

    public Songs() {
    }

	
    public Songs(SongsId id) {
        this.id = id;
    }
    public Songs(SongsId id, String album, Double duracion, String ano) {
       this.id = id;
       this.album = album;
       this.duracion = duracion;
       this.ano = ano;
    }
   
    public SongsId getId() {
        return this.id;
    }
    
    public void setId(SongsId id) {
        this.id = id;
    }
    public String getAlbum() {
        return this.album;
    }
    
    public void setAlbum(String album) {
        this.album = album;
    }
    public Double getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Double duracion) {
        this.duracion = duracion;
    }
    public String getAno() {
        return this.ano;
    }
    
    public void setAno(String ano) {
        this.ano = ano;
    }




}


